import type { Metadata } from "next";
import { ErrorBoundary } from "react-error-boundary";

import "./globals.css";

import { Footer } from "@components/Footer";
import { Navbar } from "@components/Navbar";
import { ErrorFallback } from "@components/ErrorFallback";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Elio Gerges - Software Engineer",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Google Tag Manager */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-5JWFGN9F');
            `,
          }}
        />
        {/* End Google Tag Manager */}
        <meta name="google-adsense-account" content="ca-pub-1039385271790053"/>
      </Head>
      <body
        className="antialiased w-[100vw] min-h-[100%]"
      >
        {/* <!-- Google Tag Manager (noscript) --> */}
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5JWFGN9F"
        height="0" width="0" style={{display: 'none', visibility: 'hidden'}}></iframe></noscript>
        {/* <!-- End Google Tag Manager (noscript) --> */}
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1039385271790053"
        crossOrigin="anonymous"></script>
          <Navbar />
          <div
            className="min-h-[50rem] w-full max-w-[100vw] overflow-x-hidden dark:bg-black bg-white  dark:bg-dot-white/[0.2] bg-dot-black/[0.2] relative flex items-center justify-center"
          >
            {/* <div
              className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"
            ></div> */}
            <ErrorBoundary
              FallbackComponent={ErrorFallback}
            >
              {children}
            </ErrorBoundary>
          </div>
          <Footer />
      </body>
    </html>
  );
}
