import type { Metadata } from "next";
import { ErrorBoundary } from "react-error-boundary";

import "./globals.css";

import { Footer } from "@components/Footer";
import { Navbar } from "@components/Navbar";
import { ErrorFallback } from "@components/ErrorFallback";

export const metadata: Metadata = {
  title: "Elio Gerges - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased w-[100vw] min-h-[100%]"
      >
        <ErrorBoundary
          FallbackComponent={ErrorFallback}
        >
          <Navbar />
          <div
            className="min-h-[50rem] w-full max-w-[100vw] overflow-x-hidden dark:bg-black bg-white  dark:bg-dot-white/[0.2] bg-dot-black/[0.2] relative flex items-center justify-center"
          >
            {/* <div
              className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"
            ></div> */}
            {children}
          </div>
          <Footer />
        </ErrorBoundary>
      </body>
    </html>
  );
}
